name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Accessing repo
        uses: actions/checkout@v2
      - name: Running Cypress
        uses: cypress-io/github-action@v2
        with:
          record: true
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
