name: First GitHub Action
on: [push]
jobs:
  log-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "GitHub action running!"
      - run: echo "one job can have multiple steps"
  build-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
      - name: Installing node modules
          run: yard
      - name: Building the project
          run: yarn build
      - name: Node JS Setup finished
          run: echo "NPM Installed"
