name: First GitHub Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
      - name: Installing node modules
        run: yarn
      - name: Node JS Setup finished
        run: echo "NPM Installed"
